### ISSUE TITLE
make submit button go to a win screen

### ISSUE THREAD

**Issue by angusmason** [angusmason/theaccountgame#26]

**Comment by circles-png** [comment]
draw it

**Comment by angusmason** [comment]
it should be really unsatisfying, like:

Password created.

**Comment by angusmason** [comment]
actually, the screen should be blank except for this text centered in the center:

Password created. Final password:
              {password}

**Comment by angusmason** [comment]
but center aligned

**Comment by circles-png** [comment]
centred in the centre but centre aligned

**Comment by circles-png** [comment]
done in a58fef44d02cb3a1eb9da2663f5d1ef15afdf8e3?
